name:  Preprocess Data and Upload Artifact
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Preprocessing Script
        run: python preprocess/dialouge_preprocess.py

      - name: Upload Processed Data as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: ./data/dialogue/dialog_preprocessed.pkl
          retention-days: 7  # Keeps the artifact for 7 days

      - name: Log completion
        run: echo "Preprocessing completed and uploaded as artifact at $(date)"


# name: Preprocess Data and Upload to Supabase

# on:
#   schedule:
#     - cron: '0 0 * * *'   # Runs every 10 minutes
#   workflow_dispatch:

# jobs:
#   preprocess:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Install dependencies
#         run: |
#           pip install -r requirements.txt

#       - name: Run Preprocessing and Upload to Supabase
#         env:
#           SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
#           SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
#         run: python preprocess_api_sample/preprocess/upload_to_supabase.py

#       - name: Log completion
#         run: echo "Preprocessing completed and uploaded to Supabase at $(date)"
