name: Preprocess Data Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Preprocessing Script
        run: python preprocess_api_sample/preprocess/dialouge_preprocess.py

      - name: Log completion
        run: echo "Preprocessing completed at $(date)"
